DEV: Reorganizing Github Actions

diff --git a/.github/workflows/code.yml b/.github/workflows/code.yml
--- a/.github/workflows/code.yml
+++ b/.github/workflows/code.yml
@@ -32,6 +32,11 @@ jobs:
         with:
           php-version: ${{ matrix.php-versions }}
 
+      # Start the MySQL service - https://github.com/actions/virtual-environments/blob/main/images/linux/Ubuntu1804-README.md#mysql
+      - name: Start the MySQL service
+        run: |
+          sudo systemctl start mysql.service
+
       - name: Initilize and check all dependencies
         run: |
           # Before running composer install, check that the autoloader is up-to-date and all classes can be loaded.
@@ -48,14 +53,13 @@ jobs:
           composer install -vvv
           ./vendor/bin/phpunit --version
 
-      - name: Set up PHP
+      - name: Set up Apache+PHP
         run: |
-          # Set up the PHP. No Apache, nor Mysql needed.
+          # Set up PHP
           sudo apt-get update > /dev/null
-          sudo apt install php -y
+          sudo apt install php php-mysql php8.0-mysql php7.2-mysql -y
 
           # Give permision to access files
-          # NB: not sure if needed
           setfacl -dR -m u:www-data:rwX -m u:$(whoami):rwx ./tmp
           setfacl -dR -m u:www-data:rwX -m u:$(whoami):rwx ./upload
           setfacl -dR -m u:www-data:rwX -m u:$(whoami):rwx ./themes
@@ -69,6 +73,32 @@ jobs:
           chmod -R 777 ./tests/tmp
           chmod -R 777 ./application/config
           chmod +x ./tests/bin/lint-*
+
+      - name: Check MySQL service
+        run: |
+          # InnoDB needs large_file_prefix & Barracuda file format
+          # https://discuss.gogs.io/t/solved-mysql-error-1064-while-running-first-install/1604
+          # InnoDB variables ARE already set to desired values in Github runner (ubuntu-18.04)
+
+          sudo systemctl start mysql
+          sudo service mysql status
+          mysql -uroot -proot -e "ALTER USER 'root'@'localhost' IDENTIFIED WITH mysql_native_password BY 'root';" || true
+          mysql -uroot -proot -e "Show  variables like '%large%';"
+          mysql -uroot -proot -e "Show  variables like '%innodb_file%';"
+          mysql -uroot -proot -e "Show  variables like '%innodb_default%';"
+          mysql -uroot -proot -e "CREATE DATABASE limesurvey;"
+
+      - name: Load custom console and start the Application
+        run: |
+          cp application/config/config-sample-mysql.php application/config/config.php
+          php application/commands/console.php install admin password TravisLS no@email.com verbose
+
+          # Enable debug=2 in config file. OBS: This assumes debug is on line 61.
+          # TODO: Disable, a lines was added to config file and some tests started to fail.
+          # NB: EmCache is always disabled when debug => 2
+          # NB: There can be a difference in assets used when debug = 0 or 2 (minified version or not)
+          # sed -i '60s/.*/        "debug"=>2,/' application/config/config.php
+          # cat application/config/config.php
 
       - name: Run syntax check, CodeSniffer, MessDetector, ...
         run: composer test
